### ISSUE TITLE
Rehaul design and layout for arhadthedev.net

### ISSUE THREAD

**Issue by arhadthedev** [arhadthedev/arhadthedev#1]
# As-Is

Currently it's a mere stub:

> ![image](https://user-images.githubusercontent.com/4881073/168228168-72da626e-401b-4979-b1aa-69c259e6f5df.png)

# To-Be

I'm more keen of blog post layouts like:

- https://snarky.ca/what-the-heck-is-pyproject-toml/ (*Tall, Snarky Canadian* blog)
- https://semakin.dev/2020/04/requirements_txt/ (*Pythonic Attacks* blog)
- https://mariusschulz.com/blog/optional-chaining-the-operator-in-typescript (Marius Schulz blog)

Highlights of features I'd like to borrow:

- from the *Tall, Snarky Canadian*:

  - a title bar: one-line, left-aligned, simple, wide but with limited width
    > ![](https://user-images.githubusercontent.com/4881073/168229562-66cf1d8a-0e8f-4e31-8501-1f2e7c51698d.png)

   - a page switcher:
     > ![](https://user-images.githubusercontent.com/4881073/168229919-70803c47-3869-410c-b421-4f955e9eb8c0.png)

   - list of tags below a title, not below a post
     > ![](https://user-images.githubusercontent.com/4881073/168230142-26038320-8ebb-4c34-a32a-03f64ebc1d8d.png)

- from the *Pythonic Attacks*:
  - Open Sans font in the page header
  - even simplier page header's top line (minus background)
    ![](https://user-images.githubusercontent.com/4881073/168231734-15c7b5ac-ecac-4a11-8671-375aec907cdb.png)
  - "Title - published - author - updated" article header layout
    ![](https://user-images.githubusercontent.com/4881073/168231909-8e52eeec-1983-470a-aef4-8b62ff22b890.png)

  - GitHub Issue-driven comment section
  - a gray color of a page footer
  - the site hero is the blog content, not a branding of the author. The only place where you can see a photo and a full name is "About the Author" section. Note: the URL is the author's name while the site behind has its own name expressed in a title

- from the Marius Schulz's blog:
  - Segoe UI font in the body

  - darker color of header links and their wide click area with little deadzones inbetween

    > ![](https://user-images.githubusercontent.com/4881073/168231236-0d3429f2-5a23-41fb-9818-c7ed48155cc2.png)

- extra: from GitHub Docs:
  - a link to the next article as another H2-caption
    > ![](https://user-images.githubusercontent.com/4881073/168233066-cc503b64-be9f-4ff2-9072-2f3e918714f2.png)

# To-Do

To recast it into a proper blog, the following steps are required:

- [ ] An empty title page with a generated header
- [ ] A dedicated "About Me" page
- [ ] Add the first blog post in `On this site` tag/section on how to deploy a multilanguage site
- [ ] Pulling a generator and layout into arhadthedev/arhadthedev-ru to generate the Russian language version of the site
- [ ] A main page with multicolumn tags-categories.

**Comment by arhadthedev** [comment]
Another, fresh idea: https://www.furygpu.com/blog/furygpu-texture-units

![image](https://github.com/arhadthedev/arhadthedev/assets/4881073/c69acf5f-f37b-4205-b82b-a511de98d55d)

**Comment by arhadthedev** [comment]
In three years I finally found a non-intrusive oldschool style, <https://www.linusakesson.net/scene/kaleidoscopico/index.php>:

![Image](https://github.com/user-attachments/assets/47d0462c-e72a-45a6-973b-75bbc72dc7ef)
